language: cpp


script:
    - ls /usr/bin
    - mkdir _build
    - cd _build && cmake ..
    - make -C _build pcc_raun

notifications:
  email:
    recipients:
      - xstill@fi.muni.cz
    on_success: change # default: change
    on_failure: always # default: always

sudo: false

matrix:
  include:
    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - g++-7
      env:
        - CC=gcc-7 CXX=g++-7
    - env:
        - CC=/usr/local/clang-5.0.0/bin/clang CXX=/usr/local/clang-5.0.0/bin/clang++
